version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8888:80/tcp"
    environment:
      - PUID=1000
      - UGID=1000
      - TZ=Europe/Paris
      - WEBPASSWORD={{ pihole_web_password }}
    volumes:
      - /node/data/pihole/etc-pihole:/etc/pihole
      - /node/data/pihole/etc-dnsmasq:/etc/dnsmasq.d
    restart: always
