version: "3"

networks:
  traefik:
    external: true

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - UGID=1000
      - TZ=Europe/Paris
    volumes:
      - /node/data/mediaserver/transmission/config:/config
      - /node/data/media/downloads:/data/downloads
    network_mode: container:mullvad
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.node.local`)"
      - "traefik.http.routers.transmission.entrypoints=web"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - UGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - /node/data/mediaserver/jackett/config:/config
    network_mode: container:mullvad
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.node.local`)"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.http.routers.jackett.service=jackett"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /node/data/mediaserver/radarr/config:/config
      - /node/data/media:/data
    network_mode: container:mullvad
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.node.local`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /node/data/mediaserver/jellyfin/config:/config
      - /node/data/media/movies:/data/media/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.node.local`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
      - traefik
