version: "3"

networks:
  default:
    external: false
  traefik:
    external: true

services:
  server:
    image: gitea/gitea:1.18
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD={{ gitea_db_password }}
    restart: always
    networks:
      - default
      - traefik
    volumes:
      - /node/data/gitea/data:/data
      - /home/git/.ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2222:22"
    depends_on:
       - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.localhost`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{ gitea_db_root_password }}
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD={{ gitea_db_password }}
      - MYSQL_DATABASE=gitea
    networks:
      - default
    volumes:
      - /node/data/gitea/mysql:/var/lib/mysql
