version: "3"

services:
  gateway:
    image: qmcgaw/gluetun
    container_name: mullvad
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={{ mullvad_private_key }}
      - WIREGUARD_ADDRESSES={{ mullvad_address }}
      - SERVER_COUNTRIES=Norway,Switzerland
      - OWNED_ONLY=yes
    ports:
      {{ mullvad_ports | to_nice_yaml | indent(6) }}
